# Generated by Django 6.0.7 on 2026-07-28 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('code', models.CharField(help_text='Трилітерний код аеропорту, наприклад KBP', max_length=3, unique=True, verbose_name='Код IATA')),
            ],
            options={
                'verbose_name': 'Аеропорт',
                'verbose_name_plural': 'Аеропорти',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Час вильоту')),
                ('arrival_time', models.DateTimeField(verbose_name='Час прильоту')),
                ('airline', models.CharField(max_length=100, verbose_name='Авіакомпанія')),
                ('aircraft', models.CharField(blank=True, max_length=100, verbose_name='Тип літака')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('available_seats', models.PositiveIntegerField(verbose_name='Вільні місця')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport', verbose_name='Аеропорт прильоту')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport', verbose_name='Аеропорт вильоту')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейси',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ пасажира')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість місць')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
